[package]
name = "zad6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_wrapper = { path = "../rust_wrapper/" }
